export const auth = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE'
};

export const document = {
  GET_ALL_SUCCESS: 'GET_ALL_DOCS_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_DOCS_FAILURE',
  GET_SUCCESS: 'GET_DOCUMENT_SUCCESS',
  GET_FAILURE: 'GET_DOCUMENT_FAILURE',
  SEARCH_SUCCESS: 'DOCUMENT_SEARCH_SUCCESS',
  SEARCH_FAILURE: 'DOCUMENT_SEARCH_FAILURE',
  CREATE_SUCCESS: 'DOCUMENT_CREATE_SUCCESS',
  CREATE_FAILURE: 'DOCUMENT_CREATE_FAILURE',
  UPDATE_SUCCESS: 'DOCUMENT_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'DOCUMENT_UPDATE_FAILURE',
  DELETE_SUCCESS: 'DOCUMENT_DELETE_SUCCESS',
  DELETE_FAILURE: 'DOCUMENT_DELETE_FAILURE'
};
