export const auth = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE'
};

export const document = {
  GET_ALL_SUCCESS: 'GET_ALL_DOCS_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_DOCS_FAILURE',
  SEARCH_SUCCESS: 'DOCUMENT_SEARCH_SUCCESS',
  SEARCH_FAILURE: 'DOCUMENT_SEARCH_FAILURE'
};
